"""clean initial schema

Revision ID: 7762ee95a04c
Revises: 
Create Date: 2026-02-02 15:19:48.823237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7762ee95a04c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('specialization_property_type', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('specialization_areas', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('language_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('active_leads_count', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('active_leads_count <= 50', name='ck_active_leads_max'),
    sa.CheckConstraint('active_leads_count >= 0', name='ck_active_leads_nonneg'),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('lead_scoring_rules',
    sa.Column('rule_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('score_adjustment', sa.Integer(), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('leads',
    sa.Column('lead_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('language_preference', sa.String(length=20), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('preferred_areas', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='new', nullable=False),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("source_type IN ('bayut', 'propertyFinder', 'dubizzle', 'website', 'walk_in', 'referral')", name='ck_source_type'),
    sa.CheckConstraint("status IN ('new', 'contacted', 'qualified', 'viewing_scheduled', 'negotiation', 'converted', 'lost')", name='ck_lead_status'),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name='ck_score_range'),
    sa.PrimaryKeyConstraint('lead_id'),
    sa.UniqueConstraint('phone', 'source_type', name='uq_phone_source')
    )
    op.create_table('agent_performance_metrics',
    sa.Column('metric_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_deal_size', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('average_response_time', sa.Interval(), nullable=True),
    sa.Column('leads_handled', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('follow_up_tasks',
    sa.Column('task_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("priority IN ('high', 'medium', 'low')", name='ck_task_priority'),
    sa.CheckConstraint("status IN ('pending', 'completed', 'overdue')", name='ck_task_status'),
    sa.CheckConstraint("type IN ('call', 'email', 'whatsapp', 'viewing')", name='ck_task_type'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('lead_activities',
    sa.Column('activity_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("outcome IN ('positive', 'negative', 'neutral') OR outcome IS NULL", name='ck_activity_outcome'),
    sa.CheckConstraint("type IN ('call', 'email', 'whatsapp', 'viewing', 'meeting', 'offer_made')", name='ck_activity_type'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('lead_assignments',
    sa.Column('assignment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('lead_id', name='uq_lead_assignment')
    )
    op.create_table('lead_conversion_history',
    sa.Column('history_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('status_from', sa.String(length=50), nullable=True),
    sa.Column('status_to', sa.String(length=50), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('lead_property_interests',
    sa.Column('interest_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('interest_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("interest_level IN ('high', 'medium', 'low')", name='ck_interest_level'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interest_id')
    )
    op.create_table('lead_sources',
    sa.Column('source_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('referrer_agent_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("source_type IN ('bayut', 'propertyFinder', 'dubizzle', 'website', 'walk_in', 'referral')", name='ck_source_type'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_agent_id'], ['agents.agent_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_sources')
    op.drop_table('lead_property_interests')
    op.drop_table('lead_conversion_history')
    op.drop_table('lead_assignments')
    op.drop_table('lead_activities')
    op.drop_table('follow_up_tasks')
    op.drop_table('agent_performance_metrics')
    op.drop_table('leads')
    op.drop_table('lead_scoring_rules')
    op.drop_table('agents')
    # ### end Alembic commands ###
