"""add timestamps to leads

Revision ID: 924be657aed4
Revises: 7762ee95a04c
Create Date: 2026-02-02 17:29:38.808415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924be657aed4'
down_revision = '7762ee95a04c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('leads', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'updated_at')
    op.drop_column('leads', 'created_at')
    # ### end Alembic commands ###
